pub mod day1;
pub mod day2;
pub mod day3;
pub mod day4;
pub mod day5;
pub mod day6;
pub mod day7;
pub mod day8;
pub mod day9;
pub mod day10;
pub mod day11;
pub mod day12;
pub mod day13;
pub mod day14;
pub mod day15;
pub mod day16;
pub mod day17;
pub mod day18;
pub mod day19;
pub mod day20;
pub mod day21;
pub mod day22;
pub mod day23;
pub mod day24;
pub mod day25;

pub fn run_all() {
    println!("Day 1");
    day1::run();
    println!("Day 2");
    day2::run();
    println!("Day 3");
    day3::run();
    println!("Day 4");
    day4::run();
    println!("Day 5");
    day5::run();
    println!("Day 6");
    day6::run();
    println!("Day 7");
    day7::run();
    println!("Day 8");
    day8::run();
    println!("Day 9");
    day9::run();
    println!("Day 10");
    day10::run();
    println!("Day 11");
    day11::run();
    println!("Day 12");
    day12::run();
    println!("Day 13");
    day13::run();
    println!("Day 14");
    day14::run();
    println!("Day 15");
    day15::run();
    println!("Day 16");
    day16::run();
    println!("Day 17");
    day17::run();
    println!("Day 18");
    day18::run();
    println!("Day 19");
    day19::run();
    println!("Day 20");
    day20::run();
    println!("Day 21");
    day21::run();
    println!("Day 22");
    day22::run();
    println!("Day 23");
    day23::run();
    println!("Day 24");
    day24::run();
    println!("Day 25");
    day25::run();
}
